service: streamersunleashed-api
provider: 
  name: aws
  region: us-east-2
  
      
package:
  individually: true

plugins:
  - serverless-bundle

iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - ssm:GetParameter
      Resource: 
        - "arn:aws:dynamodb:us-east-2:*:*"
        - "arn:aws:ssm:us-east-2:*:*"



functions:
  streamlabsAccess:
    handler: streamlabsAccess.main
    events:
      - http:
          path: streamlabsAccess
          method: post
          cors: true
          Auth:
            ApiKeyRequired: false
          
  profile:
    handler: profile.main
    events:
      - http:
          path: profile
          method: post
          cors: true
          Auth:
            ApiKeyRequired: false
    
  tokenMap:
    handler: tokenMap.main
    events:
      - http:
          path: tokenMap
          method: post
          cors: true
          Auth:
            ApiKeyRequired: false
  donate:
    handler: donate.main
    events:
      - http:
          path: donate
          method: post
          cors: true
          Auth:
            ApiKeyRequired: false


resources: # CloudFormation template syntax
  - ${file(resources/api-gateway-errors.yml)}
  - ${file(resources/dynamodb.yml)}
  
    