service: streamersunleashed-api
provider: 
  name: aws
  region: us-east-2
  
      
package:
  individually: true

plugins:
  - serverless-bundle

iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 
        - "arn:aws:dynamodb:us-east-2:*:*"


functions:
  streamlabsAccess:
    handler: streamlabsAccess.main
    events:
      - http:
          path: streamlabsAccess
          method: post
          cors: true
          
  profile:
    handler: profile.main
    events:
      - http:
          path: profile
          method: post
          cors: true
         


resources: # CloudFormation template syntax
  - ${file(resources/api-gateway-errors.yml)}
  - ${file(resources/dynamodb.yml)}
  
    