Resources:
    customerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: customerTable
        AttributeDefinitions:
          - AttributeName: walletAddress
            AttributeType: S
        KeySchema:
          - AttributeName: walletAddress
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1